services:
  laravel:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - laravel
    networks:
      - laravel-network

  # postgres:
  #   image: postgres:15
  #   env_file:
  #     - ./.env
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_DB: "${DB_DATABASE}"
  #     POSTGRES_USER: "${DB_USER}"
  #     POSTGRES_PASSWORD: "${DB_PASSWORD}"
  #   volumes:
  #     - database:/var/lib/postgresql/data
  #     - ./Migration/Initialization/structure.sql:/docker-entrypoint-initdb.d/structure.sql
  #   networks:
  #     - laravel-network

  redis:
    image: "redis:7.0"
    restart: always
    ports:
      - "6379:6379"
    networks:
      - laravel-network

  ngrok:
    image: wernight/ngrok
    command: ngrok http nginx:80
    ports:
      - "4040:4040"
    environment:
      NGROK_AUTHTOKEN: "${NGROK_AUTHTOKEN}"
    depends_on:
      - nginx
    networks:
      - laravel-network

volumes:
  database:

networks:
  laravel-network:
    driver: bridge
